spring:
    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:mem:test
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true

logging.level:
    org.hibernate.SQL: debug

place-finder:
    api:
        google:
            use: false
            api-key: "AIzaSyD0qqnjqXZ4O9FYiscr9_2Tp9ek54w6H6M"
        kakao:
            url: "https://dapi.kakao.com/v2/local/search/keyword.json"
            authorization: "KakaoAK 404a45f1f807e70cf6d65ffb4d9f15ff"
        naver:
            url: "https://openapi.naver.com/v1/search/local.json"
            naver-client-id: "uEZkpCtEdTGnxaK9BswC"
            naver-client-secret-id: "QQ6BSywDcm"
